/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import Modelos.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jonat
 */
public class Tela extends javax.swing.JFrame {
   
        Estudante aluno = null;
        Trabalhador funcionario = null;
        Graduado formado = null;
   
    public Tela() {
        initComponents();
        this.setLocationRelativeTo(null);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Teste = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Saida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Teste.setText("teste");
        jButton_Teste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(jButton_Teste)
                .addGap(291, 291, 291))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton_Teste)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTextArea_Saida.setColumns(20);
        jTextArea_Saida.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Saida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TesteActionPerformed
        // TODO add your handling code here:
        try {
            //Estudante
             aluno = new Estudante("johnathan"," rua 1",984799894,"jonathanm095@gmail.com",
                     95,"ads", 2);
             
             String saida = "Dados da pessoa: \n";
             saida+= "Nome: "+ aluno.getNome()+"\n";
             saida+= "Endereço: "+aluno.getEndereco()+"\n";
             saida+= "Telefone: "+aluno.getTelefone()+"\n";
             saida+= "Email: "+ aluno.getEmail()+"\n";
             saida+= aluno.toString()+"\n";
            
             saida+= "--------------------------------------------------------- \n";
             
             //Trabalhador
             funcionario = new Trabalhador("Maria", "Rua 10",99990000,"maria@googlie.com",
                     "Diretora", "Diretoria", 5000);
             saida+= "Dados da pessoa \n";
             saida+= "Nome: "+ funcionario.getNome()+"\n";
             saida+= "Endereço: "+funcionario.getEndereco()+"\n";
             saida+= "Telefone: "+funcionario.getTelefone()+"\n";
             saida+= "Email: "+ funcionario.getEmail()+"\n";
             saida+= funcionario.toString()+"\n";
             saida+= "--------------------------------------------------------- \n";
             
             //Graduado
             formado = new Graduado("Luiz"," rua 7",0100021025,"Luiz@gmail.com",
                     0001,"Ads",02, 2019, 2020, 1000);
              saida+= "Dados da pessoa \n";
             saida+= "Nome: "+ formado.getNome()+"\n";
             saida+= "Endereço: "+formado.getEndereco()+"\n";
             saida+= "Telefone: "+formado.getTelefone()+"\n";
             saida+= "Email: "+ formado.getEmail()+"\n";
             saida+= formado.toString()+"\n";
             saida+= "---------------------------------------------------------\n";
             
             jTextArea_Saida.setText(saida);
        
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this,erro.getMessage());
        }
       
    }//GEN-LAST:event_jButton_TesteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Teste;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Saida;
    // End of variables declaration//GEN-END:variables
}
