package visao;

import javax.swing.JOptionPane;
import modelos.*;

public class TelaTeste extends javax.swing.JFrame {

    ContaPoupanca poupanca = null;
    ContaCorrenteBasica correnteBasica = null;
    ContaCorrenteComLimite correnteComLimite = null;

    public TelaTeste() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_teste = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Saida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_teste.setText("teste");
        jButton_teste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_testeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton_teste)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton_teste)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTextArea_Saida.setColumns(20);
        jTextArea_Saida.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Saida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_testeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_testeActionPerformed
        try {
            // TODO add your handling code here:

            //Conta Poupança
            poupanca = new ContaPoupanca("joh", 70238139182L, 1000, 1002, 0);
            String saida = "--- Conta Poupança --- \n";
            saida += "Nome: " + poupanca.getNome() + "\n";
            saida += "CPF: " + poupanca.getCpf() + "\n";
            saida += "Agência: " + poupanca.getAgencia() + "\n";
            saida += "Conta Poupança: " + poupanca.getConta() + "\n";
            saida += "Deposito: R$" + poupanca.depositar(1100) + "\n";
            saida += "Saque: R$" + poupanca.sacar(100) + "\n";
            saida += "Saldo: R$" + poupanca.emitirSaldo() + "\n";
            saida += "Rendimento Mensal: R$" + poupanca.calcularRendimento();
            saida += "\n----------------------------------------------------------------------------\n";

            //Conta corrente basica
            correnteBasica = new ContaCorrenteBasica("joh", 70238139182L, 1000, 1002, 0);
            saida += "--- Conta corrente Basica --- \n";
            saida += "Nome: " + correnteBasica.getNome() + "\n";
            saida += "CPF: " + correnteBasica.getCpf() + "\n";
            saida += "Agência: " + correnteBasica.getAgencia() + "\n";
            saida += "Conta Poupança: " + correnteBasica.getConta() + "\n";
            saida += "Deposito: R$" + correnteBasica.depositar(1100) + "\n";
            saida += "Saque: R$" + correnteBasica.sacar(150) + "\n";
            saida += "Tarifa bancária: R$" + correnteBasica.calcularTarifa() + "\n";
            saida += "Saldo: R$" + correnteBasica.emitirSaldo() + "\n";
            saida += "\n----------------------------------------------------------------------------\n";
            
            //Conta corrente com Limite
            correnteComLimite = new ContaCorrenteComLimite("joh", 70238139182L, 1000, 1002, 0);
            saida += "--- Conta corrente com Limite --- \n";
            saida += "Nome: " + correnteComLimite.getNome() + "\n";
            saida += "CPF: " + correnteComLimite.getCpf() + "\n";
            saida += "Agência: " + correnteComLimite.getAgencia() + "\n";
            saida += "Conta Poupança: " + correnteComLimite.getConta() + "\n";
            saida += "Deposito: R$" + correnteComLimite.depositar(200) + "\n";
            saida += "Saque: R$" + correnteComLimite.sacar(1100) + "\n";
            saida += "Tarifa bancária: R$" + correnteComLimite.calcularTarifa() + "\n";
            saida+= "Limite da Conta: R$"+correnteComLimite.calcularLimite()+"\n";
            saida += "Saldo com Limite: R$" + correnteComLimite.emitirSaldo() + "\n";
            

            jTextArea_Saida.setText(saida);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }//GEN-LAST:event_jButton_testeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_teste;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Saida;
    // End of variables declaration//GEN-END:variables
}
